In [10]:
import pandas as pd
pd.set_option('display.max_seq_items', None)

In [ ]:
df = pd.read_csv("Data/openfoodfacts-products.csv", sep="\t", low_memory=False, on_bad_lines="skip")
df.head()
# Temps : 2m 1.8s

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g,water_100g
0,54,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1582569031,2020-02-24T18:30:31Z,1733085204,2024-12-01T20:33:24Z,NaN,1.740205e+09,2025-02-22T06:23:42Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1673620307,2023-01-13T14:31:47Z,1750061386,2025-06-16T08:09:46Z,bodysupport,1.750061e+09,2025-06-16T08:09:46Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1580066482,2020-01-26T19:21:22Z,1751035658,2025-06-27T14:47:38Z,teolemon,1.751036e+09,2025-06-27T14:47:38Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,431,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1714301712,2024-04-28T10:55:12Z,1714301721,2024-04-28T10:55:21Z,kiliweb,1.714302e+09,2024-04-28T10:55:21Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1572117743,2019-10-26T19:22:23Z,1738073570,2025-01-28T14:12:50Z,NaN,1.743653e+09,2025-04-03T04:11:36Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(4532765, 211)

In [11]:
df.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'last_modified_by',
       'last_updated_t', 'last_updated_datetime', 'product_name',
       'abbreviated_product_name', 'generic_name', 'quantity', 'packaging',
       'packaging_tags', 'packaging_en', 'packaging_text', 'brands',
       'brands_tags', 'brands_en', 'categories', 'categories_tags',
       'categories_en', 'origins', 'origins_tags', 'origins_en',
       'manufacturing_places', 'manufacturing_places_tags', 'labels',
       'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags',
       'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places',
       'stores', 'countries', 'countries_tags', 'countries_en',
       'ingredients_text', 'ingredients_tags', 'ingredients_analysis_tags',
       'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'serving_quantity', 'no_nutrition_data', 'additives_n',
       'additives', 'additives_tags', 'additives_en', 'nutriscore_score',
       'nutriscore_grade', 'nova_group', 'pnns_groups_1', 'pnns_groups_2',
       'food_groups', 'food_groups_tags', 'food_groups_en', 'states',
       'states_tags', 'states_en', 'brand_owner', 'environmental_score_score',
       'environmental_score_grade', 'nutrient_levels_tags', 'product_quantity',
       'owner', 'data_quality_errors_tags', 'unique_scans_n',
       'popularity_tags', 'completeness', 'last_image_t',
       'last_image_datetime', 'main_category', 'main_category_en', 'image_url',
       'image_small_url', 'image_ingredients_url',
       'image_ingredients_small_url', 'image_nutrition_url',
       'image_nutrition_small_url', 'energy-kj_100g', 'energy-kcal_100g',
       'energy_100g', 'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g',
       'butyric-acid_100g', 'caproic-acid_100g', 'caprylic-acid_100g',
       'capric-acid_100g', 'lauric-acid_100g', 'myristic-acid_100g',
       'palmitic-acid_100g', 'stearic-acid_100g', 'arachidic-acid_100g',
       'behenic-acid_100g', 'lignoceric-acid_100g', 'cerotic-acid_100g',
       'montanic-acid_100g', 'melissic-acid_100g', 'unsaturated-fat_100g',
       'monounsaturated-fat_100g', 'omega-9-fat_100g',
       'polyunsaturated-fat_100g', 'omega-3-fat_100g', 'omega-6-fat_100g',
       'alpha-linolenic-acid_100g', 'eicosapentaenoic-acid_100g',
       'docosahexaenoic-acid_100g', 'linoleic-acid_100g',
       'arachidonic-acid_100g', 'gamma-linolenic-acid_100g',
       'dihomo-gamma-linolenic-acid_100g', 'oleic-acid_100g',
       'elaidic-acid_100g', 'gondoic-acid_100g', 'mead-acid_100g',
       'erucic-acid_100g', 'nervonic-acid_100g', 'trans-fat_100g',
       'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g',
       'added-sugars_100g', 'sucrose_100g', 'glucose_100g', 'fructose_100g',
       'galactose_100g', 'lactose_100g', 'maltose_100g', 'maltodextrins_100g',
       'psicose_100g', 'starch_100g', 'polyols_100g', 'erythritol_100g',
       'isomalt_100g', 'maltitol_100g', 'sorbitol_100g', 'fiber_100g',
       'soluble-fiber_100g', 'polydextrose_100g', 'insoluble-fiber_100g',
       'proteins_100g', 'casein_100g', 'serum-proteins_100g',
       'nucleotides_100g', 'salt_100g', 'added-salt_100g', 'sodium_100g',
       'alcohol_100g', 'vitamin-a_100g', 'beta-carotene_100g',
       'vitamin-d_100g', 'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g',
       'vitamin-b1_100g', 'vitamin-b2_100g', 'vitamin-pp_100g',
       'vitamin-b6_100g', 'vitamin-b9_100g', 'folates_100g',
       'vitamin-b12_100g', 'biotin_100g', 'pantothenic-acid_100g',
       'silica_100g', 'bicarbonate_100g', 'potassium_100g', 'chloride_100g',
       'calcium_100g', 'phosphorus_100g', 'iron_100g', 'magnesium_100g',
       'zinc_100g', 'copper_100g', 'manganese_100g', 'fluoride_100g',
       'selenium_100g', 'chromium_100g', 'molybdenum_100g', 'iodine_100g',
       'caffeine_100g', 'taurine_100g', 'methylsulfonylmethane_100g',
       'hydroxymethylbutyrate_100g', 'ph_100g',
       'fruits-vegetables-legumes_100g', 'collagen-meat-protein-ratio_100g',
       'cocoa_100g', 'chlorophyl_100g', 'carbon-footprint_100g',
       'glycemic-index_100g', 'water-hardness_100g', 'choline_100g',
       'phylloquinone_100g', 'beta-glucan_100g', 'inositol_100g',
       'carnitine_100g', 'sulphate_100g', 'nitrate_100g', 'acidity_100g',
       'carbohydrates-total_100g', 'water_100g'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4532765 entries, 0 to 4532764
Columns: 211 entries, code to water_100g
dtypes: float64(130), int64(2), object(1), str(78)
memory usage: 7.1+ GB

In [9]:
df.describe()

,created_t,last_modified_t,last_updated_t,nova_group,environmental_score_score,product_quantity,unique_scans_n,completeness,last_image_t,energy-kj_100g,...,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g,water_100g
count,4.532765e+06,4.532765e+06,4.532570e+06,1.133717e+06,882028.000000,1.382985e+06,1.578648e+06,4.532712e+06,3.472820e+06,2.199357e+06,...,38710.000000,2.325310e+05,66.000000,191.000000,164.000000,627.000000,406.000000,36.000000,1970.000000,244085.000000
mean,1.646103e+09,1.739963e+09,1.759721e+09,3.342446e+00,51.528724,2.264250e+14,3.279802e+00,4.163951e-01,1.660522e+09,7.459543e+03,...,0.022458,1.154317e-01,3.721919,0.695763,0.099452,0.198538,0.023973,5.682649,36.814180,47.906356
std,8.952494e+07,5.667297e+07,2.063513e+07,1.034895e+00,26.178171,2.654277e+17,1.535609e+01,2.048224e-01,7.744631e+07,7.051836e+06,...,2.225420,8.734246e-01,2.163014,6.607728,0.906729,2.166073,0.145515,5.527920,229.229494,32.820714
min,1.328021e+09,1.357475e+09,1.705516e+09,1.000000e+00,-30.000000,0.000000e+00,1.000000e+00,5.000000e-02,1.331578e+09,-2.333333e+03,...,0.000000,-9.858750e+00,0.400000,0.000007,0.000800,0.000000,0.000000,0.008200,0.000000,-1.305172
25%,1.581602e+09,1.728038e+09,1.743245e+09,3.000000e+00,33.000000,1.050000e+02,1.000000e+00,2.750000e-01,1.609927e+09,4.694000e+02,...,0.000000,1.114500e-07,2.300000,0.006600,0.001980,0.001000,0.000100,2.526923,6.262500,12.400000
50%,1.651317e+09,1.773390e+09,1.773391e+09,4.000000e+00,53.000000,2.500000e+02,1.000000e+00,3.750000e-01,1.660600e+09,1.069700e+03,...,0.000000,6.793000e-07,3.750000,0.008000,0.002100,0.003700,0.000370,5.750000,20.000000,54.588628
75%,1.727391e+09,1.774639e+09,1.774639e+09,4.000000e+00,71.000000,5.000000e+02,2.000000e+00,5.000000e-01,1.730615e+09,1.656400e+03,...,0.000000,3.942400e-06,4.600000,0.028500,0.010000,0.019000,0.000900,6.000000,55.496454,79.095815
max,1.779784e+09,1.779784e+09,1.779784e+09,1.380000e+02,125.000000,3.121424e+20,3.410000e+03,1.100000e+00,1.779784e+09,1.000000e+10,...,390.476190,5.400000e+01,12.666667,75.000000,11.500000,40.000000,2.000000,33.333333,10000.000000,100.000000